# Stage 1: Build
FROM node:20-alpine AS builder
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_LOG_LEVEL
ARG VITE_APP_VERSION=dev
ARG VITE_APP_BUILD_SHA=local
ARG VITE_APP_BUILD_DATE=
ARG VITE_APP_ENV=local
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_LOG_LEVEL=$VITE_LOG_LEVEL
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_APP_BUILD_SHA=$VITE_APP_BUILD_SHA
ENV VITE_APP_BUILD_DATE=$VITE_APP_BUILD_DATE
ENV VITE_APP_ENV=$VITE_APP_ENV
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]