import type { Category, Payee } from '../types'

export const DEFAULT_CATEGORIES = [
  {
    name: 'Entertainment',
    aliases: [
      'Entertainment',
      'Games',
      'Gaming',
      'Movies',
      'Movie',
      'Cinema',
      'Concerts',
      'Events',
      'Subscriptions',
      'Streaming',
      'Hobbies',
      'Fun',
    ],
  },
  {
    name: 'Health & Medical',
    aliases: [
      'Health',
      'Medical',
      'Health & Medical',
      'Healthcare',
      'Doctor',
      'Dentist',
      'Pharmacy',
      'Medication',
      'Medicine',
      'Prescriptions',
      'Personal Care',
      'Wellness',
      'Personal/Medical',
      'Medical',
      'Physical Activity',
    ],
  },
  {
    name: 'Miscellaneous',
    aliases: [
      'Miscellaneous',
      'Misc',
      'Other',
      'General',
      'Uncategorized',
      'Unknown',
      'Random',
      'One-off',
      'Adjustment',
      'Refund',
      'Gifts',
    ],
  },
  {
    name: 'Shopping',
    aliases: [
      'Shopping',
      'Clothes',
      'Clothing',
      'Apparel',
      'Shoes',
      'Accessories',
      'Electronics',
      'Material Items',
      'Personal Goods',
      'Retail',
      'Online Shopping',
    ],
  },
  {
    name: 'Transportation',
    aliases: [
      'Transportation',
      'Transport',
      'Transit',
      'TTC',
      'Presto',
      'GO Transit',
      'Uber',
      'Lyft',
      'Taxi',
      'Parking',
      'Gas',
      'Fuel',
      'Car',
    ],
  },
  {
    name: 'Groceries',
    aliases: [
      'Groceries',
      'Grocery',
      'Groc',
      'Food',
      'Supermarket',
      'Market',
      'Produce',
      'Pantry',
      'Household Groceries',
    ],
  },
  {
    name: 'Dining Out',
    aliases: [
      'Dining Out',
      'Dining',
      'Restaurant',
      'Restaurants',
      'Takeout',
      'Take-out',
      'Delivery',
      'Fast Food',
      'Coffee',
      'Cafe',
      'Bubble Tea',
      'Lunch',
      'Dinner',
      'Eating Out',
    ],
  },
  {
    name: 'Bills & Utilities',
    aliases: [
      'Bills & Utilities',
      'Bills',
      'Utilities',
      'Hydro',
      'Electricity',
      'Gas Bill',
      'Water',
      'Internet',
      'Phone',
      'Mobile',
      'Insurance',
      'Rent',
      'Subscription Bills',
    ],
  },
  {
    name: 'Home',
    aliases: [
      'Home',
      'House',
      'Household',
      'Furniture',
      'Decor',
      'Appliances',
      'Cleaning',
      'Repairs',
      'Maintenance',
      'Kitchen',
      'Bathroom',
      'Bedroom',
      'Home Improvement',
    ],
  },
  {
    name: 'Travel',
    aliases: [
      'Travel',
      'Trip',
      'Vacation',
      'Hotel',
      'Flight',
      'Flights',
      'Airfare',
      'Airbnb',
      'Cruise',
      'Luggage',
      'Travel Food',
      'Tourism',
      'Passport',
    ],
  },
  {
    name: 'Pets',
    aliases: [
      'Pets',
      'Pet',
      'Cat',
      'Dog',
      'Kitten',
      'Pet Food',
      'Cat Food',
      'Dog Food',
      'Litter',
      'Vet',
      'Veterinary',
      'Pet Supplies',
      'Pet Valu',
    ],
  },
]

export const DEFAULT_PAYEES: { name: string; aliases: string[] }[] = [
  // ── Groceries & Supermarkets ──────────────────────────────────
  {
    name: 'Loblaws',
    aliases: ['Loblaws', 'Loblaw', "Loblaw's", 'Loblaw Companies', 'Loblaws grocery'],
  },
  {
    name: 'No Frills',
    aliases: [
      'nofrills',
      'metro+nofrills+shoppers',
      'No Frills',
      'No Frills grocery',
      'No Frills groc',
    ],
  },
  {
    name: 'Metro',
    aliases: ['Metro', 'metro+nofrills+shoppers', 'Metro grocery', 'Metro groc'],
  },
  { name: 'Sobeys', aliases: ['Sobeys', "Sobey's", 'Sobeys grocery'] },
  { name: 'FreshCo', aliases: ['FreshCo', 'Fresh Co', 'FreshCo grocery'] },
  {
    name: 'Walmart',
    aliases: [
      'Walmart',
      'Walmart order',
      'Walmart Snorkel',
      'Walmart nivea',
      'walmart groc',
      'Walmart pet stuff',
      'Walmart pet food',
      'Walmart haul',
      'Wal-Mart',
      'Walmart Supercentre',
      'Walmart grocery',
    ],
  },
  {
    name: 'Costco',
    aliases: [
      'Costco',
      'Costco run',
      'costco food',
      'Costco split',
      'Groc costco',
      'Costco+ foodie',
      'Costco groc',
      'costco',
      'Costco Wholesale',
      'Costco grocery',
    ],
  },
  {
    name: 'T&T Supermarket',
    aliases: [
      'T&T',
      'T & T',
      'T&T Supermarket',
      'T and T',
      'Tnt supermarket',
      'Tt groc',
      'T&t groc',
    ],
  },
  { name: 'Farm Boy', aliases: ['Farm Boy', 'Farmboy', 'Farm Boy grocery'] },
  {
    name: 'FoodieMart',
    aliases: [
      'Foodiemart',
      'foodiemart',
      'Foodiemart groc',
      'Foodymart',
      'Foody Mart',
      'Foodie Mart',
      'Foodymart groc',
    ],
  },
  {
    name: 'Foodyworld',
    aliases: ['Foodyworld', 'Foody World', 'Foody World grocery'],
  },
  { name: 'FreshWay Foodmart', aliases: ['Freshway', 'freshway'] },
  {
    name: 'Bestco',
    aliases: ['Bestco', 'Bestco Fresh Food Mart', 'Bestco grocery', 'Bestco groc'],
  },
  {
    name: 'Shoppers Drug Mart',
    aliases: [
      'Shoppers',
      'Shoppers groc',
      'metro+nofrills+shoppers',
      'Shoppers Drug Mart',
      'SDM',
      'Pharmaprix',
      'Shoppers pharmacy',
    ],
  },
  {
    name: 'Rexall',
    aliases: ['Rexall', 'Rexall Pharmacy', 'Rexall Pharma Plus'],
  },
  // ── Dining & Coffee ───────────────────────────────────────────
  {
    name: 'Tim Hortons',
    aliases: [
      'Timmies',
      "Tim's",
      'Tims',
      'Tim+big beef',
      'Tim Hortons',
      "Tim Horton's",
      'Tim Horton',
    ],
  },
  { name: 'Starbucks', aliases: ['Starbucks', 'Starbucks Coffee', 'Sbux'] },
  {
    name: "McDonald's",
    aliases: [
      'Mcdonald',
      'Mcdonalds',
      'mcdonalds',
      'mcdoland',
      'Mcdoland',
      'Macd',
      "McDonald's",
      'McD',
    ],
  },
  { name: 'Subway', aliases: ['Subway', 'subway', 'Subway Sandwiches'] },
  { name: 'Pizza Pizza', aliases: ['Pizza pizza', 'Pizzapizza'] },
  { name: 'Pizza Hut', aliases: ['pizza hut', 'Pizza hut'] },
  { name: "Harvey's", aliases: ["Harvey's", 'Harveys', 'Harvey'] },
  { name: 'Swiss Chalet', aliases: ['Swiss Chalet', 'Swisschalet'] },
  {
    name: 'The Keg',
    aliases: ['The Keg', 'Keg', 'Keg Steakhouse', 'The Keg Steakhouse'],
  },
  { name: 'A&W', aliases: ['AW', 'A&w', 'Moonstone gas + aw'] },
  { name: 'KFC', aliases: ['Kfc', 'KFC'] },
  { name: 'Popeyes', aliases: ['Popeyes', 'popeyes', 'Popeyes+booster'] },
  { name: "Church's Chicken", aliases: ['Churchs', 'doordash churchs'] },
  { name: 'Chipotle', aliases: ['Chipotle', 'Chipot'] },
  {
    name: 'Coco Fresh Tea & Juice',
    aliases: [
      'Coco',
      'coco',
      'minus coco',
      'Lazeez + coco',
      'coco+padthai',
      'Coco+pho',
      'Coco Fresh Tea',
      'Coco Fresh Tea & Juice',
      'Coco Tea',
      'Coco bubble tea',
    ],
  },
  {
    name: 'Real Fruit Bubble Tea',
    aliases: ['Real fruit', 'realfruit', 'Realfruit'],
  },
  { name: 'Chatime', aliases: ['chatime'] },
  { name: 'The Alley', aliases: ['Alley'] },
  {
    name: 'Molly Tea',
    aliases: ['Molly Tea', 'Mollytea', 'Molly Tea Toronto', 'Molly bubble tea'],
  },
  { name: "Osmow's", aliases: ['Osmow', 'osmow', 'Osmows', 'Uber osmow'] },
  {
    name: 'Bolet / Bole Burrito',
    aliases: ['Bolet', 'bolet', 'bole burrito', 'Bolel burritos', 'bolel again'],
  },
  { name: 'JCP', aliases: ['JCP', 'Jcp', 'jcp', 'uber eats jcp cancel'] },
  { name: 'Lazeez', aliases: ['Lazeez', 'Lazeez + coco'] },
  { name: 'Jimmy the Greek', aliases: ['Jimmy the greek', 'Jimmy the Greek'] },
  { name: 'Chamsine', aliases: ['Chamseen', 'Chamsine', 'chamsine'] },
  { name: 'NYF', aliases: ['Nyf', 'NYF'] },
  { name: 'Boustan', aliases: ['Boustan', 'Boustan shwarma'] },
  { name: 'Rolltation', aliases: ['Rolltation', 'rolltation'] },
  { name: 'Daimaru', aliases: ['Daimaru', 'daimaru'] },
  { name: 'Brown Donkatsu', aliases: ['Brown donkatsu', 'brown donkatsu'] },
  { name: 'Mogouyan', aliases: ['Mogouyan'] },
  { name: 'Noodle Legend', aliases: ['Noodle legend', 'noodle legend'] },
  { name: 'Haidilao', aliases: ['haidilao', 'Haidilao'] },
  { name: 'Gyubee', aliases: ['Gyubee'] },
  { name: 'Dragon Legend', aliases: ['Dragon Legend', 'Dragon legend'] },
  { name: 'Ramen Isshin', aliases: ['Ramen isshin', 'Ramen Isshin'] },
  { name: 'China Cottage', aliases: ['China cottage'] },
  { name: 'Hey Noodles', aliases: ['Heynood'] },
  { name: 'Yakiniku Like', aliases: ['Yakiniku LIke', 'yakiniku like'] },
  {
    name: 'Uber Eats',
    aliases: ['Uber Eats', 'Ubereats', 'Uber *Eats', 'Uber Eats order'],
  },
  {
    name: 'DoorDash',
    aliases: ['DoorDash', 'Door Dash', 'DD', 'DD Canada', 'Doordash order'],
  },
  {
    name: 'SkipTheDishes',
    aliases: ['SkipTheDishes', 'Skip The Dishes', 'Skip', 'Skip order'],
  },
  { name: 'LCBO', aliases: ['LCBO', 'Liquor Control Board of Ontario'] },
  {
    name: 'Beer Store',
    aliases: ['Beer Store', 'The Beer Store', 'Beerstore'],
  },
  // ── Transit & Transportation ──────────────────────────────────
  {
    name: 'TTC',
    aliases: ['TTC', 'Toronto Transit Commission', 'TTC fare', 'TTC pass'],
  },
  {
    name: 'PRESTO',
    aliases: [
      'Presto',
      'presto',
      'Presto Reload',
      'presto recharge',
      'PResto',
      'Presto card',
      'Presto load',
    ],
  },
  {
    name: 'GO Transit',
    aliases: ['GO Transit', 'GO Train', 'GO Bus', 'Metrolinx GO', 'GO fare'],
  },
  {
    name: 'UP Express',
    aliases: ['UP Express', 'Union Pearson Express', 'UPX', 'UP Express fare'],
  },
  {
    name: 'Uber',
    aliases: [
      'Uber',
      'Uber grand one chicken',
      'Uber osmow',
      'uber hospital',
      'uber eats jcp cancel',
      'Uber to aunt',
      'Texas Uber',
      'Uber Trip',
      'Uber *Trip',
      'Uber ride',
      'help.uber.com',
    ],
  },
  { name: 'Lyft', aliases: ['Lyft', 'Lyft ride', 'Lyft Trip'] },
  { name: '407 ETR', aliases: ['407'] },
  { name: 'Shell', aliases: ['Shell Gas'] },
  {
    name: 'Green P Parking',
    aliases: ['Green P', 'Green P Parking', 'Toronto Parking Authority', 'TPA Parking', 'GreenP'],
  },
  { name: 'Impark', aliases: ['Impark', 'Imperial Parking', 'Impark Parking'] },
  // ── Utilities & Telecom ───────────────────────────────────────
  {
    name: 'Toronto Hydro',
    aliases: [
      'Toronto Hydro',
      'Toronto Hydro-Electric',
      'Toronto Hydro Electric System',
      'Hydro bill',
    ],
  },
  {
    name: 'Enbridge Gas',
    aliases: ['Enbridge', 'Enbridge Gas', 'Enbridge Gas Inc', 'Gas bill'],
  },
  {
    name: 'Rogers',
    aliases: [
      'Rogers',
      'Rogers Communications',
      'Rogers Wireless',
      'Rogers Internet',
      'Rogers bill',
    ],
  },
  {
    name: 'Bell',
    aliases: ['Bell', 'Bell Canada', 'Bell Mobility', 'Bell Internet', 'Bell bill'],
  },
  { name: 'Telus', aliases: ['Telus', 'Telus Mobility', 'Telus bill'] },
  {
    name: 'Fido',
    aliases: ['Fido setup fee', 'Fido', 'Fido Mobile', 'Fido bill'],
  },
  {
    name: 'Freedom Mobile',
    aliases: ['Freedom Mobile', 'Freedom', 'Freedom bill'],
  },
  { name: 'Koodo', aliases: ['Koodo', 'Koodo Mobile', 'Koodo bill'] },
  {
    name: 'Virgin Plus',
    aliases: ['Virgin extra fees', 'Virgin insurance', 'Virgin Long distance'],
  },
  { name: 'Ubigi', aliases: ['Ubigi'] },
  // ── Banking & Finance ─────────────────────────────────────────
  {
    name: 'RBC',
    aliases: ['RBC', 'Royal Bank', 'Royal Bank of Canada', 'RBC fee', 'RBC Visa'],
  },
  {
    name: 'TD Bank',
    aliases: ['TD', 'TD Bank', 'TD Canada Trust', 'Toronto Dominion', 'TD fee', 'TD Visa'],
  },
  {
    name: 'Scotiabank',
    aliases: ['Scotiabank', 'Scotia', 'Bank of Nova Scotia', 'Scotia fee', 'Scotia Visa'],
  },
  {
    name: 'BMO',
    aliases: ['BMO', 'Bank of Montreal', 'BMO fee', 'BMO Mastercard'],
  },
  {
    name: 'CIBC',
    aliases: ['CIBC', 'Canadian Imperial Bank of Commerce', 'CIBC fee', 'CIBC Visa'],
  },
  {
    name: 'Tangerine',
    aliases: ['Tangerine', 'Tangerine Bank', 'Tangerine fee'],
  },
  { name: 'EQ Bank', aliases: ['EQ Bank', 'Equitable Bank', 'EQ'] },
  // ── Retail & Shopping ─────────────────────────────────────────
  {
    name: 'Amazon',
    aliases: [
      'Amazon',
      'Amazon haul',
      'Amazon Kitten Stuff',
      'Amazon Watch strap',
      'Amazon.ca',
      'AMZN',
      'AMZN MKTP',
      'Amazon Marketplace',
      'Amazon order',
    ],
  },
  {
    name: 'Temu',
    aliases: ['Temu', 'Temu haul', 'Temu order', 'temu stuff', 'Temu haul2', 'White board temu'],
  },
  {
    name: 'Uniqlo',
    aliases: ['Uniqlo', 'uniqlo haul', 'Uniqlo shirt', 'Uniqlo shirts'],
  },
  { name: 'IKEA', aliases: ['Ikea', 'Ikea stuff', 'ikea return'] },
  {
    name: 'Winners',
    aliases: ['Winners', 'bracelet winners', 'Winners shorts', 'Winners outing', 'Winners haul'],
  },
  { name: 'HomeSense', aliases: ['Homesense'] },
  { name: 'H&M', aliases: ['H&M', 'H and M', 'HM', 'Hennes Mauritz'] },
  { name: 'Zara', aliases: ['zara', 'Zara return', 'Zara Canada'] },
  { name: 'MUJI', aliases: ['muji'] },
  {
    name: 'Canadian Tire',
    aliases: ['Canadian Tire', 'Cdn Tire', 'CTC', 'CanadianTire'],
  },
  {
    name: 'Home Depot',
    aliases: ['Home Depot', 'The Home Depot', 'Homedepot'],
  },
  { name: 'Best Buy', aliases: ['Best Buy', 'Bestbuy', 'Best Buy Canada'] },
  { name: 'Sport Chek', aliases: ['Sport Chek', 'Sportchek', 'Sport Check'] },
  { name: 'Dollarama', aliases: ['Dollarama Haul', 'dollarama'] },
  { name: 'Value Village', aliases: ['value village', 'Value village'] },
  { name: 'Grailed', aliases: ['Grailed haul', 'grailed refund'] },
  { name: 'Buyee', aliases: ['Buyee duties'] },
  { name: 'FromJapan', aliases: ['Fromjapan shipping', 'Duties fromjapan'] },
  { name: 'Aliexpress', aliases: ['AliExpress', 'Ali Express', 'Ali stuff'] },
  { name: 'Shein', aliases: ['Shein', 'Shein order'] },
  { name: 'SSENSE', aliases: ['SSENSE', 'SSENSE Canada'] },
  {
    name: 'Facebook Marketplace',
    aliases: ['FB Market', 'FB Marketplace', 'Facebook Marketplace', 'Marketplace'],
  },
  { name: 'Poshmark', aliases: ['Poshmark', 'Poshmark Canada'] },
  { name: 'Etsy', aliases: ['Etsy', 'Etsy Canada', 'Etsy order'] },
  {
    name: 'Indigo',
    aliases: ['Indigo', 'Chapters', 'Indigo Books', 'Chapters Indigo'],
  },
  {
    name: 'Apple',
    aliases: ['Apple', 'Apple Store', 'Apple.com', 'Apple Services', 'iCloud', 'Apple Canada'],
  },
  { name: 'Pet Valu', aliases: ['Pet Valu Food', 'petvalu'] },
  // ── Entertainment & Subscriptions ─────────────────────────────
  {
    name: 'Netflix',
    aliases: ['PAYPAL NETFLIX', 'PAYPAL *NETFLIX', 'Netflix', 'Netflix.com', 'Netflix CA'],
  },
  { name: 'Spotify', aliases: ['Spotify', 'Spotify Premium', 'Spotify CA'] },
  {
    name: 'Disney+',
    aliases: ['Disney+', 'Disney Plus', 'Disneyplus', 'Disney Plus Canada'],
  },
  { name: 'Crave', aliases: ['Crave', 'Crave TV', 'CraveTV', 'Bell Crave'] },
  {
    name: 'YouTube Premium',
    aliases: ['YouTube Premium', 'YouTube', 'Google YouTube'],
  },
  {
    name: 'Apple TV+',
    aliases: ['Apple TV+', 'Apple TV Plus', 'Apple TV', 'Apple Services'],
  },
  {
    name: 'Xbox Game Pass',
    aliases: ['Xbox Game Pass', 'Game Pass', 'Microsoft Game Pass', 'Xbox', 'Microsoft Xbox'],
  },
  {
    name: 'Blizzard / Battle.net',
    aliases: ['Blizzard', 'blizz sub', 'Diablo 4'],
  },
  {
    name: "Canada's Wonderland",
    aliases: ['Wonderland', 'wonderland', 'Wonderland food', 'Gold pass'],
  },
  // ── Health & Wellness ─────────────────────────────────────────
  { name: 'GoodLife Fitness', aliases: ['GoodLife', 'GoodLife Fitness'] },
  { name: 'Planet Fitness', aliases: ['Planet Fitness', 'PlanetFitness'] },
  { name: 'OHIP', aliases: ['OHIP', 'Ontario Health Insurance Plan'] },
  // ── Services & Other ──────────────────────────────────────────
  {
    name: 'Canada Post',
    aliases: ['Canada Post', 'Canadapost', 'Post Office', 'Canada Post shipping'],
  },
  {
    name: 'FedEx',
    aliases: ['FedEx', 'Federal Express', 'FedEx shipping', 'FedEx duties'],
  },
  {
    name: 'UPS',
    aliases: ['UPS', 'United Parcel Service', 'UPS fee', 'UPS duties', 'UPS shipping'],
  },
  {
    name: 'City of Toronto',
    aliases: [
      'City of Toronto',
      'Toronto Property Tax',
      'Toronto Utility Bill',
      'Toronto Water',
      'Municipal Licensing',
    ],
  },
  {
    name: 'Service Ontario',
    aliases: [
      'Service Ontario',
      'ServiceOntario',
      'Ontario Service',
      'Drivers license renewal',
      'Renew drivers license',
    ],
  },
]

// ── Income & Savings Snapshots ────────────────────────────

export function buildDefaultCategories(now: string): Category[] {
  return DEFAULT_CATEGORIES.map((category) => ({
    name: category.name,
    cloudId: crypto.randomUUID(),
    createdAt: now,
    updatedAt: now,
    isArchived: false,
  }))
}

export function buildDefaultPayees(now: string): Payee[] {
  return DEFAULT_PAYEES.map(({ name, aliases }) => ({
    name,
    cloudId: crypto.randomUUID(),
    aliases: aliases ?? [],
    createdAt: now,
    updatedAt: now,
    isArchived: false,
  }))
}
